package com.example.shortletBackend.enums;

public enum PropertyType {
    HOUSE,APARTMENT,BARN,BED_AND_BREAKFAST,
    BOAT,CABIN,CAMPER,CASTLE,CAVE,CONTAINER,
    EARTH_HOME,FARM,GUESTHOUSE,HOTEL,HOUSEBOAT,
    HUT,RYOKAN,SHEPHERDS_HUT,TENT,TINY_HOME,
    TOWER,TREEHOUSE,WINDMILL,YURT
}
