create table amenities (id bigint not null auto_increment, air_condition bit not null, bbq_grill bit not null, beach_access bit not null, fire_extinguisher bit not null, fireplace bit not null, first_aid_kit bit not null, free_parking bit not null, hot_tub bit not null, kitchen bit not null, lake_access bit not null, outdoor_dining bit not null, outdoor_shower bit not null, paid_parking bit not null, patio bit not null, pool bit not null, pool_table bit not null, smoke_alarm bit not null, tv bit not null, washer bit not null, wifi bit not null, work_space bit not null, primary key (id)) engine=InnoDB;
create table apartments (id bigint not null auto_increment, address varchar(255), cleaning_fee integer not null, continent varchar(255), country varchar(255), description longtext, home_state varchar(255), house_ref_code varchar(255), house_type varchar(255), max_no_of_guests integer not null, name varchar(255), no_of_bathrooms integer not null, no_of_bedrooms integer not null, no_of_beds integer not null, price integer not null, property_type varchar(255), rating double precision not null, service_fee integer not null, state varchar(255), status varchar(255), amenities_id bigint, users_id bigint, primary key (id)) engine=InnoDB;
create table apartments_pictures (apartments_id bigint not null, pictures_id bigint not null) engine=InnoDB;
create table comments (id bigint not null auto_increment, comment longtext, comment_date date, apartments_id bigint, users_id bigint, primary key (id)) engine=InnoDB;
create table pictures (id bigint not null auto_increment, url longtext, primary key (id)) engine=InnoDB;
create table reservation (id bigint not null auto_increment, check_in_date date, check_out_date date, price integer not null, reservation_state varchar(255), apartment_id bigint, users_id bigint, primary key (id)) engine=InnoDB;
create table review (id bigint not null auto_increment, review double precision not null, apartments_id bigint, users_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), name varchar(255), phone_no varchar(255), picture longtext, role varchar(255), primary key (id)) engine=InnoDB;
alter table apartments_pictures add constraint UK_41uw60oibih9f1t49douy50yv unique (pictures_id);
alter table apartments add constraint FKr795hgq4yc8wev8nr1dm9ytbr foreign key (amenities_id) references amenities (id);
alter table apartments add constraint FKscql5m2pfi58av6dbee52tqcy foreign key (users_id) references users (id);
alter table apartments_pictures add constraint FKjvkis8s4cwb7rsjj9dyjgp5go foreign key (pictures_id) references pictures (id);
alter table apartments_pictures add constraint FKofafpj4sbnrc27mh4ytwxdnu0 foreign key (apartments_id) references apartments (id);
alter table comments add constraint FK3glbruu7kxoit58wjl8a6r8ru foreign key (apartments_id) references apartments (id);
alter table comments add constraint FKt55y2infwbbw3o942o2mhm0v4 foreign key (users_id) references users (id);
alter table reservation add constraint FKivm4eucnmrfspa4s2e4j5x0th foreign key (apartment_id) references apartments (id);
alter table reservation add constraint FK15w8lrbqikmtjwas4jalyrawq foreign key (users_id) references users (id);
alter table review add constraint FKo7hosrw55j37pft1llrsyxl2h foreign key (apartments_id) references apartments (id);
alter table review add constraint FKg6eq2th3bvlqun9ri060j8hak foreign key (users_id) references users (id);
